
CREATE DATABASE SENAC;
USE SENAC;
CREATE TABLE CURSO(
    id INT AUTO_INCREMENT,
    nome VARCHAR(200) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    PRIMARY KEY(id)
);

-- USE SENAC;
-- ALTER TABLE CURSO ADD COLUMN descricao VARCHAR(200) NOT NULL;